### ISSUE TITLE
tunes tooltips - handle "\n"

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#105]
"\n" should become "<br/>"?

![image](https://user-images.githubusercontent.com/48498823/94957088-30db3580-04bb-11eb-9a1f-b991e0c72151.png)

**Comment by timination** [comment]
Hi, I don't know your code structure so I won't submit a PR, but if this is an HTML "title" attribute, try replacing `\n` with `&#013;&#010;`

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/b1f02c70e238a034bf7e4c2845333971447467d2
