### ISSUE TITLE
"Unsupported file format version!" MLV can open rusEFI SD card log but rusEFI cannot :(

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#107]
Attached log file opens in MegaLogViewer but on with REO

![image](https://user-images.githubusercontent.com/48498823/95527331-f2ee7d80-09a2-11eb-80bb-f17418bbe474.png)

![image](https://user-images.githubusercontent.com/48498823/95527344-03065d00-09a3-11eb-96da-4970fef481f1.png)
[re_37.zip](https://github.com/rusefi/web_backend/files/5351869/re_37.zip)

**Comment by andreika-git** [comment]
Are we sure that we want to open corrupted files, no matter what?
Especially when we already have https://github.com/rusefi/rusefi/pull/1867/commits/82c8d10844736c2b8821e3ea3ad0b5a96d3a0d6e commit by @mck1117 which supposedly fixed the issue?

**Comment by mck1117** [comment]
a related question: do we actually need the `time` channel? There's already a timestamp embedded in every data frame.

**Comment by andreika-git** [comment]
Time channel is related to 'continuity' problem, when there are several ECU starts (reboots) in 1 log file (with time resets). I don't know if it's possible to handle it correctly using only embedded timestamps...

**Comment by mck1117** [comment]
ah yes, I guess you can't detect an ecu reboot without looking for gaps in samples unless you have a "time since boot" channel.  I guess it's reasonable to keep it then!

**Comment by rusefillc** [comment]
Hard to tell for sure but it looks like @andreika-git is saying that the file in question is corrupted.

I've tested with fresh file and things are looking better, closing ticket
