### ISSUE TITLE
tune is not well

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#109]
https://rusefi.com/online/view.php?msq=272

**Comment by rusefillc** [comment]
@Abricosvw can you please attached currenttune.msq as a .zip archieve?

**Comment by Abricosvw** [comment]
[11.7.2020.zip](https://github.com/rusefi/web_backend/files/5507563/11.7.2020.zip)

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/9520972f210e976d57ca27606b0672774ab8bf08
