### ISSUE TITLE
something wrong with log 74

### ISSUE THREAD

**Issue by mck1117** [rusefi/web_backend#112]
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/568254/101705359-9c9dc980-3a3b-11eb-9561-9da0a6135b41.png">

this does not look right

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/161617589-5fc7f774-3f73-41cd-9249-4db01852b072.png)

Fixed.
