### ISSUE TITLE
tune compare is broken maybe around tables or floats

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#128]
https://rusefi.com/online/diff.php?msq1=598&msq2=594

why is injector dead time on the diff?

![image](https://user-images.githubusercontent.com/48498823/126874211-3ad441de-1838-47f7-bf71-b5432b27845e.png)

**Comment by andreika-git** [comment]
Now we compare all fields using a decimal precision specified in the ini-files (or 2 decimal digits if precision is not set for a field).
![image](https://user-images.githubusercontent.com/15104768/147871159-1847520f-11ce-496b-9f72-a1b401989cf8.png)
