### ISSUE TITLE
unable to upload h7 tune

### ISSUE THREAD

**Issue by mck1117** [rusefi/web_backend#138]
![image](https://user-images.githubusercontent.com/568254/145302429-5450f4f3-c254-4367-9211-00f0f18ec19e.png)

**Comment by rusefillc** [comment]
@mck1117 can you still reproduce this? please attach affected tune

**Comment by mck1117** [comment]
Still happens with H7 proteus tunes.

![image](https://user-images.githubusercontent.com/568254/150412987-3a125f05-6a2b-4d18-8a9c-2d3dc0a945ae.png)

[CurrentTune.zip](https://github.com/rusefi/web_backend/files/7908150/CurrentTune.zip)

**Comment by mck1117** [comment]
Additional datapoint: TunerStudio also can't automatically find the ini for an H7.

**Comment by mck1117** [comment]
`proteus_h7` folder missing from https://rusefi.com/online/ini/rusefi/2022/01/20/
