### ISSUE TITLE
tune upload error "file is truncated"

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/web_backend#139]
Using snapshot_20211205_155629_hellen72_rusefi, i am unable to upload tunes to rusefionline.  I have not had this issue on previous releases.  Error screenshot below.  

![image](https://user-images.githubusercontent.com/82395131/145696868-acdcdd9b-261c-4646-91f1-aff7fbe4c208.png)

**Comment by BeerMoneyMotorsports** [comment]
Please let me know what additional info i can supply.  I have no clue where to start.

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports please attach a recent sample of affected log file
