### ISSUE TITLE
REO log upload failure

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/web_backend#143]
I am seeing failures to upload logs to REO. Tunes load fine.  

After clicking upload, it sits for a while then displays the message below.  I can email the particular log as need or if there is another action to help diagnose the problem?

![image](https://user-images.githubusercontent.com/82395131/148624788-06f057a6-af7c-4c13-9443-add1d7f7a5ca.png)

**Comment by BeerMoneyMotorsports** [comment]
[2022-01-05_18.37.20.zip](https://github.com/rusefi/web_backend/files/7832246/2022-01-05_18.37.20.zip)

**Comment by BeerMoneyMotorsports** [comment]
Any help?  This is transforming from nuisance to problem.

**Comment by rusefillc** [comment]
I wonder if that's related to #147

please attach an example of a log which fails to upload for you

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc please see the zip that was attached.

**Comment by BeerMoneyMotorsports** [comment]
failure seems to correspond with but not always happen when i get the message below. 

![image](https://user-images.githubusercontent.com/82395131/149825138-56b2faa4-0d8b-491e-af5d-b40053313418.png)
