### ISSUE TITLE
Tables contain only 0

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/web_backend#144]
When reviewing some tunes, some tables were populated with only 0 and one table shows incorrect description.  Unsure how many other tables have this issue but here are 2 examples.  Tune for reference https://rusefi.com/online/view.php?msq=807
1- Boost control Open and closed loop tables
<img width="191" alt="image" src="https://user-images.githubusercontent.com/82395131/148658688-5dad803f-05a0-4ae6-adc2-168b06f58bea.png">

2- TPS/TPS Acceleration Extra Fuel (ms) comes up with a table that has incorrect name(HPFP) and all 0s.
<img width="142" alt="image" src="https://user-images.githubusercontent.com/82395131/148658815-c9a272cb-6f3b-4681-b1f8-aead5ccedee3.png">

**Comment by BeerMoneyMotorsports** [comment]
zip of tune
[CurrentTune.zip](https://github.com/rusefi/web_backend/files/7833967/CurrentTune.zip)

**Comment by andreika-git** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15104768/148681826-eab7893c-d7d2-4a01-a659-422d487cabf4.png)

**Comment by BeerMoneyMotorsports** [comment]
@andreika-git @rusefillc thank you, closing
