### ISSUE TITLE
GitHub Action to upload www folder to 1and1

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#146]
www folder here is just file repository without any direct link to 1and1

Until today files are uploaded manually, let's do fancy and have www folder upload programmatically with GHA?

**Comment by chuckwagoncomputing** [comment]
Having 2 scripts both uploading shouldn't be a problem as long as they don't touch any of the same files.

**Comment by chuckwagoncomputing** [comment]
#148

**Comment by rusefillc** [comment]
@chuckwagoncomputing any idea why no uploads of most recent commits?

https://github.com/rusefi/web_backend/commits/master

also I do not have manual action invocation button if I recall it's location right :(

**Comment by chuckwagoncomputing** [comment]
Looks like it worked to me. The redirects are working properly.

**Comment by rusefillc** [comment]
oh there was some sort of a delay
