### ISSUE TITLE
'trg_err' renamed - only 'time' and RPM should be mandatory fields?

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/web_backend#158]
cannot upload logs to REO due to below error.  

![image](https://user-images.githubusercontent.com/82395131/161449480-1fdfe89b-adc5-4bd1-8ea5-3b9f78023535.png)

**Comment by rusefillc** [comment]
@andreika-git this field was recently renamed

expected: logs should upload file regardless of pretty minor fields. 

it's my understanding that TS allows users to select what fields to log

I'say that ideally only "time" and "RPM" should be mandatory fields

**Comment by rusefillc** [comment]
At the moment no fresh log could be uploaded to REO.

**Comment by mck1117** [comment]
we could also rename it back in the firmware

**Comment by andreika-git** [comment]
1) "'trg_err' renamed" - what's the current (new) name? I'll add it to the web_backend.
2) or can you attach any of the logs which contain the new name?

**Comment by mck1117** [comment]
@andreika-git the log linked on this tune has the new field: https://github.com/rusefi/rusefi/issues/4041

**Comment by andreika-git** [comment]
> @andreika-git the log linked on this issue has the new field: [rusefi/rusefi#4041](https://github.com/rusefi/rusefi/issues/4041)

Thanks! Hopefully done.

**Comment by rusefillc** [comment]
3. in my opinion we should support files without this field. TS has UI for custom fields selection and SD card is often behind TS - ideally we need REO to be more fault tolerant in general, and "no field" is a totally valid user input anyway.
