### ISSUE TITLE
diff page layout

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#161]
I have a 27 inch wide screen and I open https://rusefi.com/online/diff.php?msq1=944&msq2=921&page=7

problem: this diff report somehow does not fit on my screen in Chrome?
smaller problem: center line is not centered

![image](https://user-images.githubusercontent.com/48498823/162633155-188be291-c11d-46a5-a98c-f11a30d32d4c.png)

**Comment by andreika-git** [comment]
Hopefully done
(needs refreshing)
