### ISSUE TITLE
diff report: two shades of yellow maybe?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#162]
problem: if you have too many differences you get too many yellow lines merged together like

![image](https://user-images.githubusercontent.com/48498823/162633277-b466b928-18a7-4962-a5a9-84012bd6a21a.png)

to make it easier to read can we distinguish lines somehow? maybe alternate two different background colors? maybe line spaces between lines? not sure HOW but please consider some way to split the huge solid yellow block

**Comment by andreika-git** [comment]
Hopefully done.
(needs refreshing)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/162634526-7521c450-d915-430b-a3a6-66ccd4ecd466.png)

LOOKS GREAT THANK YOU!!!!
