### ISSUE TITLE
'Search' link shows bad default

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#163]
open https://rusefi.com/online/
click "search"
https://rusefi.com/online/search.php shows some profanity default, we shall remove that 

![image](https://user-images.githubusercontent.com/48498823/162649026-e86450d0-bc6a-4aeb-aaa8-c18789adcc49.png)

**Comment by andreika-git** [comment]
done?

**Comment by rusefillc** [comment]
Thank you!
