### ISSUE TITLE
RusEFI datalog and rusEFI online issues

### ISSUE THREAD

**Issue by ElDominio** [rusefi/web_backend#166]
![image](https://user-images.githubusercontent.com/5685108/164071851-7cd5b164-0a3a-40ad-8f21-1065b2ee14d3.png)

The newest firmware update is making logs that throw this error, haven't seen this before

**Comment by andreika-git** [comment]
Can you please attach the log file which causes the issue?

**Comment by rusefillc** [comment]
This seems to be related to .mlq field limit 34
``$mlgFieldFmt = "cType/a34Name/a11Units/GScale/GShift/cPrecision";``

**Comment by rusefillc** [comment]
@ElDominio do you still have the file? plz .zip and attach here?

**Comment by ElDominio** [comment]
[idledrop.zip](https://github.com/rusefi/web_backend/files/8516476/idledrop.zip)

**Comment by rusefillc** [comment]
@andreika-git poke

I've added length validation into code generator and apparently we have a lot of fields with long names for instance "fuel: Barometric pressure correction"

Does this "fuel: Barometric pressure correction" work in TS somehow?

**Comment by andreika-git** [comment]
> Does this "fuel: Barometric pressure correction" work in TS somehow?

I don't see this full name inside the idledrop.mlg by ElDominio. I see only truncated names like "fuel: Barometric pressure correcti" or "cranking_coolantTemperatureCoeffic". I don't see any example of the "34 character" rule violation.

**Comment by ElDominio** [comment]
Close
