### ISSUE TITLE
data rate

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#167]
a very important statistics for us is log file data rate, would it be possible to add it?

![image](https://user-images.githubusercontent.com/48498823/164227075-564013db-17ea-4527-b907-ab8f34ce43a6.png)

**Comment by andreika-git** [comment]
Isn't it already implemented?
![image](https://user-images.githubusercontent.com/15104768/164227568-6a705731-d209-4198-9c77-cd776f5d98b4.png)

**Comment by rusefillc** [comment]
either I am blind or it's a usability issue

I was focusing on the right since that's where all the stats are

can we move info block

![image](https://user-images.githubusercontent.com/48498823/164228017-178c2605-e1f3-420c-a9f5-d1c81d7f759d.png)

to the right above 

![image](https://user-images.githubusercontent.com/48498823/164228038-f1e07fd8-0869-40f5-8ca9-feb921539cf4.png)

**Comment by rusefillc** [comment]
https://rusefi.com/online/view.php?log=753
