### ISSUE TITLE
scary warnings

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#170]
curDialog

![image](https://user-images.githubusercontent.com/48498823/165401714-4f181d05-382d-4850-ab2e-71e5519eae1d.png)

https://rusefi.com/online/view.php?msq=975

![image](https://user-images.githubusercontent.com/48498823/165401768-5a343140-f7de-49d8-bccf-b363bb6b080c.png)

**Comment by mi-hol** [comment]
@rusefillc another one to close
