### ISSUE TITLE
simple very noticable marketing vinyl for 760IL

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#173]
Planning to attend a lemons race on June 10th, planning to take my 760IL.

Thinking to ask Mark to print some vinyl. Matybe just a repetative stripe of some sort, maybe a cross on the hood and a stipe along the body? The goal is to be somewhat removable since using public parking so a stripe of 3-4 inches wide sounds appealing

Q1: what color choice would be most visible on the grey/green body?
Q2: do we need any text copy?
Q3: need help with files

**Comment by rusefillc** [comment]
![20211015_173348](https://user-images.githubusercontent.com/48498823/171517796-a066b98a-7bf2-467c-ac4e-8a74a213d02f.jpg)
![20211015_173451](https://user-images.githubusercontent.com/48498823/171517806-ac452030-7ddd-4e0b-b26b-e00d404b60a7.jpg)
![20211015_173334](https://user-images.githubusercontent.com/48498823/171517811-87bc61db-6d85-44cb-844f-440c5a3aacc5.jpg)
![20211015_173342](https://user-images.githubusercontent.com/48498823/171517819-e6e2abad-f0e0-4a19-ad79-3fc783b8ef00.jpg)

**Comment by rusefillc** [comment]
@mck1117 this is the repo with https://github.com/rusefi/web_backend/tree/master/www/style so kind of right

**Comment by rusefillc** [comment]
maybe
https://github.com/rusefi/web_backend/blob/master/www/style/rusefi.png long
and the following text below or after:

"Drive by Wire - CAN bus - Lua Scripting - Knock Detection - rusefi.com - "

**Comment by rusefillc** [comment]
@NMSTEC what are file requirments? DPI?

**Comment by billstewartx** [comment]
use vector art, so no DPI needed

**Comment by NMSTEC** [comment]
Vector files please, and if using odd font, please convert to the outlines. Please embed any used images.

Eps/ai preffered. Cut lines with bleed would be preffered if it's some special design.

**Comment by rusefillc** [comment]
![stripe](https://user-images.githubusercontent.com/48498823/171533004-18410a91-23dd-465d-a197-3b4a88438dbd.gif)

See https://github.com/rusefi/web_backend/blob/master/www/style/svg/stripe.xcf fir GIMP vector format, can you make a tape/strire of it by copy-pasting it 18 times?

**Comment by NMSTEC** [comment]
Honestly in my opinion that looks terrible. But yes we can, give me dimensions please

**Comment by rusefillc** [comment]
one sticker can we go 9.68 inch by 2 inch? (not 3 inch as file stands at the moment?)

9.68 copy-pasted 5 times continuesly makes one stripe would be 48.4

Car length 200 inches. Can I please have 400 inches of this give or take?

So 2 inches by 50 inches you said? 8 times?

**Comment by NMSTEC** [comment]
Sure. We'll attach spares, and I'll still make my employee his take on it, and see what he can do for additional graphics.

**Comment by billstewartx** [comment]
you left off VEE-12 cylinders !
the car is 12 cyl... 
and the rusefi does 12 cyl

**Comment by billstewartx** [comment]
plus-
all the "A"  and e and D and o and b and a etc are gonna have the inside area drop off during vinyl cutting / production 
so the type will look crappy, or you have to go through and place each center hole
![Screen Shot 2022-06-02 at 6 46 48 AM](https://user-images.githubusercontent.com/74264678/171613431-87837d5e-caa2-4547-9173-3292cff475b1.png)
 by hand 
you need type that holds the inside, like this

**Comment by billstewartx** [comment]
mark, if you want to print out a graphic for my car hood, and throw it into the package for andrey, i can put the graphic on my car  when we get to NJMP on jun 11. 
my hood is ~ 1300 x 900 MM  max graphic size...
feel free to whip up something you like... i have no preconceived notions ...

**Comment by NMSTEC** [comment]
Im unable to open or convert xcf file to anything I can use. Please change to any common format.

**Comment by rusefillc** [comment]
now .eps at https://github.com/rusefi/web_backend/tree/master/www/style/svg
