### ISSUE TITLE
Document font

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#174]
What font does https://github.com/rusefi/web_backend/tree/master/www/style/svg use? 

let's document in https://github.com/rusefi/web_backend/blob/master/www/style/svg/readme.md

**Comment by rusefillc** [comment]
@ksmola

**Comment by mi-hol** [comment]
@rusefillc please grant me permission to update issues in this repo or close this one yourself

**Comment by rusefillc** [comment]
@mi-hol just granted doc-team triage access to this repo please test by closing this ticket?
