### ISSUE TITLE
MLQ v2 support

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#185]
MLQ v2 is a minor but incompatible format change with higher limit on fields and cagegory field in records

https://www.efianalytics.com/TunerStudio/docs/MLG_Binary_LogFormat_2.0.pdf

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/210884143-4310ef6f-4a0f-4bb4-8f0b-8f03270db455.png)
