### ISSUE TITLE
Error uploading log

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/web_backend#188]
Log taken today on NA6 with todays firmware.  Tune uploaded fine however none of the logs would upload from todays tests.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/82395131/190932172-7148f198-dd35-4e58-a896-d3aee2c33967.png">

<img width="162" alt="image" src="https://user-images.githubusercontent.com/82395131/190932209-d7053d1b-8230-4fe1-a845-d3ac8804cab3.png">

**Comment by rusefillc** [comment]
no actionable without actual log. Please reopen if you are able to attached the compressed log on the ticket.

**Comment by BeerMoneyMotorsports** [comment]
Closing the case so quickly is not productive.  Here is the log per your request.  I did not realize i could upload after compressing.  


[flex.zip](https://github.com/rusefi/web_backend/files/9595501/flex.zip)

**Comment by BeerMoneyMotorsports** [comment]
seeing no response here but also seeing no issues uploading recent logs.
