### ISSUE TITLE
tunes to contain namespace

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#211]
I am failing to have same java code read locally produced tunes and tunes downloaded from rusefi online due to XML namespace difference

local tunes from real Tuner Studio, same with tunes produces my rusEFI java code
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<msq xmlns="http://www.msefi.com/:msq">
```

but downloaded files like https://rusefi.com/online/download.php?msq=1238
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<msq >
```

Can we add ``xmlns="http://www.msefi.com/:msq`` into old https://rusefi.com/online/download.php?msq=1238 tune or at least into future tunes?

**Comment by andreika-git** [comment]
Done for future tunes. Unfortunately I don't remember why we kept removing xmlns from the files...

**Comment by andreika-git** [comment]
Done for all tunes
