### ISSUE TITLE
rusEFI online complainig about metada?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/web_backend#213]
<img width="483" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/f5988d62-000c-4c78-a0aa-e7ad92247f67">

trying to upload this file 
[CurrentTune.zip](https://github.com/rusefi/rusefi/files/11913328/CurrentTune.zip)

**Comment by andreika-git** [comment]
Couldn't reproduce the warning using the attached file.

But anyway I've added the 'WARNING' prefix and the list of missing fields:
![image](https://github.com/rusefi/web_backend/assets/15104768/55872588-570d-40f7-a165-b110c49eb144)

**Comment by andreika-git** [comment]
Done
