### ISSUE TITLE
merge engine make and engine code column in the UI

### ISSUE THREAD

**Issue by rusefi** [rusefi/web_backend#25]
engine make and code are logically two parts of engine family identifier

engine make and engine code should be rendered on the UI in one columns

**Comment by rusefi** [comment]
FYI @andreika-git

**Comment by andreika-git** [comment]
What's the name of the new combined column?

**Comment by rusefi** [comment]
Engine make/code

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/736b937cbb5f8e65b22bdb9186149700c038c241
