### ISSUE TITLE
engine code cleanup button

### ISSUE THREAD

**Issue by rusefi** [rusefi/web_backend#27]
on tune delete we shall see if some "engines" are no longer used and should be removed

we also need a script to purge historically dead entities on demand

special URL available only for two Andrey's

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/619908ee335e333a6a952d1baf1f44b7c64ed0a9

**Comment by rusefi** [comment]
@andreika-git can you please paste the magic purge tool URL here?

**Comment by andreika-git** [comment]
https://rusefi.com/online/?action=engines_cleanup
