### ISSUE TITLE
tune diff functionality

### ISSUE THREAD

**Issue by rusefi** [rusefi/web_backend#28]
once you are on the list of vehicle tunes it should be possible to select two tunes for comparison. we need a new column with checkboxes with java script enabling "compare" button only if exactly two checkboxes are selected

by default top two tunes should be selected

the "compare" button should be located above the list table, to the right from "show 100" control

a new page is needed showing the list of different parameters, curves and tables

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/0322fafe7d29e8b948eb876502061a2fe733ae91
