### ISSUE TITLE
Tune Note column

### ISSUE THREAD

**Issue by rusefi** [rusefi/web_backend#39]
We need new column with human readable summary of what makes this specific tune interesting

Users should be able to edit tune note after the fact

Tune note should be currently limited to 128 characters

**Comment by rusefi** [comment]
Tune Note column would be displayed before Cylinders column

**Comment by andreika-git** [comment]
Maybe we could use the existing feature of TS?
![image](https://user-images.githubusercontent.com/15104768/85574558-8e9bee00-b63f-11ea-8c4e-e41f4bbf5c1e.png)

**Comment by rusefi** [comment]
well, i would love to have edit online

so maybe this field would be the first one to have edit online? :)

**Comment by rusefi** [comment]
on tune list view column width should be limited to 32 symbols, with mouse-over popup displaying the whole note

tune owner should have an editable control above "More about this Mazda B6ZE "Miata"

on https://rusefi.com/online/view.php?msq=42

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/0471b7e935f9577240843a420c454c65e2af0229
