### ISSUE TITLE
unable to delete tune 21

### ISSUE THREAD

**Issue by rusefi** [rusefi/web_backend#44]
I am unable to delete tune 21

the cross icon color is different from all other tunes

![image](https://user-images.githubusercontent.com/7377949/85460326-1f57c880-b571-11ea-9ddf-96b71cf9144b.png)

i say "yes" and nothing seem to be happening?
![image](https://user-images.githubusercontent.com/7377949/85460332-22eb4f80-b571-11ea-8932-e51ab219533c.png)

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/27bde94fbc337360f34f6a76161b112a37aeadae
