### ISSUE TITLE
Just uploaded a tune and got a bit of an error

### ISSUE THREAD

**Issue by rusefi** [rusefi/web_backend#49]
@stefanst says

Just uploaded a tune and got a bit of an error:
The tune file has been uploaded!
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Msqur::view(), 1 passed in /homepages/5/d451478433/htdocs/online/upload.php on line 277 and exactly 3 expected in /homepages/5/d451478433/htdocs/online/msqur.php:156 Stack trace: #0 /homepages/5/d451478433/htdocs/online/upload.php(277): Msqur->view(

**Comment by stefanst** [comment]
Here is the tune that caused
[CurrentTune.zip](https://github.com/rusefi/web_backend/files/4835006/CurrentTune.zip)

 the issue.

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/9b2864c62312013d42b103466fb6bbd72b61d593
