### ISSUE TITLE
2d curves display backwards

### ISSUE THREAD

**Issue by mck1117** [rusefi/web_backend#5]
Expected: minimum at left, maximum at right
Actual: maximum at left, minimum at right:

![image](https://user-images.githubusercontent.com/568254/81344096-0059b180-906b-11ea-82cd-d9611efe0255.png)

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/b527c40ac43efeec93dbb0220bb08b546f8611b3

![image](https://user-images.githubusercontent.com/15104768/81390434-2000e080-9124-11ea-95c1-c5fe564a2b4e.png)
