### ISSUE TITLE
Testing Strategy - we need reliability

### ISSUE THREAD

**Issue by rusefi** [rusefi/web_backend#52]
We have some pretty hard core XML parsing with PHP code here. What is our testing strategy? Any automated CI?

important note: we run PHP 7.3 in production so our Github action should use 7.3 not 7.2 not 7.4

**Comment by rusefi** [comment]
@andreika-git what was the name of the command line test utility you've got?

**Comment by andreika-git** [comment]
msqur/tests/mlg_test.php

**Comment by rusefi** [comment]
@chuckwagoncomputing we have msqur/tests/mlg_test.php and we have https://github.com/rusefi/msqur/blob/prod/tests/testcases/2020-06-30_19.21.53_mck1117_large.mlg as the first testcase

Would you be available to build GHA which ensures we can still parse that test input file? technically php has PHPUnit but it looks like no one has experience with it.

**Comment by rusefi** [comment]
See #66 - stuff was not compiling under 7.2 in prod, this was mitigated by #67

**Comment by rusefi** [comment]
Different defect - https://github.com/rusefi/rusefi/issues/1598

**Comment by chuckwagoncomputing** [comment]
Sure, I'll add it to my todo list.

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/33d5251d9f29e5660f3d12ebc239e9a5ef1261f7

**Comment by rusefi** [comment]
Wow progress! We still need a git hub action for this :)

@andreika-git what are the entry points into current test coverage?

**Comment by andreika-git** [comment]
I'm using **tests/run_tests.sh** and it outputs something like this:
`PHPUnit 9.2.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.12
Configuration: G:\rusefi\msqur\tests\phpunit.xml

Test 'TestDb::testTables' started
Test 'TestDb::testTables' ended
Test 'TestMlg::testMlgParser' started
Test 'TestMlg::testMlgParser' ended
Time elapsed: 5.0562889575958 secs
Test 'TestUpload::testTuneUpload' started
Test 'TestUpload::testTuneUpload' ended
[]

Time: 00:13.848, Memory: 138.00 MB

OK (3 tests, 9 assertions)`

**Comment by chuckwagoncomputing** [comment]
Should this action be on the msqur repo, or is it possible to break this test with changes to this repo?

**Comment by rusefi** [comment]
has to be prod branch of rusefi msqur

**Comment by rusefillc** [comment]
What is the current status @andreika-git @chuckwagoncomputing ? I know there is something somewhere, can we document?

**Comment by chuckwagoncomputing** [comment]
https://github.com/rusefi/msqur/pull/4

**Comment by rusefillc** [comment]
so close this one?

**Comment by chuckwagoncomputing** [comment]
You can close this.
