### ISSUE TITLE
broken log link

### ISSUE THREAD

**Issue by rusefi** [rusefi/web_backend#53]
User https://rusefi.com/forum/memberlist.php?mode=viewprofile&u=674 has link in the profile

link says https://rusefi.com/online/view.php?msq=48 but no such log

in reality his log is https://rusefi.com/online/view.php?msq=41

and anyway it's not working :( I guess because of default bundle not being there

Format Version: 5.0
MS Signature: rusEFI 2020.06.30.all.520656958
Tuning SW:
Date:
Unable to load the corresponding configuration file for that MSQ. Please file a bug!

**Comment by andreika-git** [comment]
It's tune, not log
But anyway, it's fixed now! :)
https://github.com/rusefi/msqur/commit/992be96b1851b47d76d40dcda50793255ad2f9d8
https://github.com/rusefi/web_backend/commit/f9e562deb1ab06ff5fb2e6612e256f4531ed93c8
