### ISSUE TITLE
link from tune page to vehicle

### ISSUE THREAD

**Issue by rusefi** [rusefi/web_backend#58]
open https://rusefi.com/online/view.php?msq=42

We need a way to open vehicle list of tunes/logs etc

**Comment by rusefi** [comment]
Can we do "More about this Mazda" above "Format Version: 5.0"?

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/1e541bb2b6f6428b518c1c785f098d5de1207b21
