### ISSUE TITLE
Unable to upload logs above 16M

### ISSUE THREAD

**Issue by rusefi** [rusefi/web_backend#59]
The current bottleneck is mysql limit, which is 16Mb

https://rusefi.slack.com/archives/C012FUD3UGL/p1594319427447900

max_allowed_packet

**Comment by rusefi** [comment]
@andreika-git  :(

https://stackoverflow.com/questions/5688403/how-to-check-and-set-max-allowed-packet-mysql-variable

**Comment by rusefi** [comment]
![image](https://user-images.githubusercontent.com/7377949/87081886-11a07500-c1f8-11ea-8ae8-9624bece346f.png)

@andreika-git

**Comment by rusefi** [comment]
https://stackoverflow.com/questions/3748/storing-images-in-db-yea-or-nay

**Comment by andreika-git** [comment]
Did you use "root" login?

**Comment by rusefi** [comment]
@andreika-git that's shared hosting, I assume I do not have root? :(

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/01b591845ccca248c3578875507e7291d5e9a7f5
