### ISSUE TITLE
table value color scale is reversed from TS

### ISSUE THREAD

**Issue by mck1117** [rusefi/web_backend#6]
expected: high values are red, low values are blue
reality: high values are blue, low values are red

![image](https://user-images.githubusercontent.com/568254/81344414-9097f680-906b-11ea-8ebc-55dd29bf6277.png)

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/bee18ff99f068a846f33b4fad21918212c94b59a

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/81376682-bb865700-910c-11ea-874b-39634ff5d7a4.png)
