### ISSUE TITLE
JSON auth service

### ISSUE THREAD

**Issue by rusefi** [rusefi/web_backend#65]
REO server needs to lookup users by auth token

A JSON service is needed which takes one auth token as a parameter and returns INVALID for invalid token, user ID and userNAME for valid token.

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/582cc8d65742962957a0abe74c62806e891bf184

https://rusefi.com/online/api.php?method=getUserByToken&rusefi_token=xxx-xxx-xxx
