### ISSUE TITLE
reduce significant figures visible

### ISSUE THREAD

**Issue by mck1117** [rusefi/web_backend#7]
This is clearly too many:
![image](https://user-images.githubusercontent.com/568254/81345359-2b450500-906d-11ea-81d5-b7f9bb3f5e3b.png)
Perhaps read the configured number of digits out of the ini like TS does?

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/c11a8163651564354c366cd9af43d58d2f6bd7de
