### ISSUE TITLE
Log to show a list of all relevant tunes

### ISSUE THREAD

**Issue by rusefi** [rusefi/web_backend#73]
On https://rusefi.com/online/view.php?log=15 we should have a table listing all timeframes which match any tunes on REO

ideally the toolset should be smart to add more links if additional tunes are loaded after log is loaded

in case of no tune matching for specific time ranges "Unknown tune" should be presented

**Comment by andreika-git** [comment]
Please specify the exact place for the table.
Please specify the format of the table (title, column names).
Please specify how the additional tunes differ from the directly related ones.

**Comment by rusefi** [comment]
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

**Comment by rusefillc** [comment]
https://rusefi.com/online/view.php?log=23 is the log

https://rusefi.com/online/view.php?msq=190
https://rusefi.com/online/view.php?msq=189
https://rusefi.com/online/view.php?msq=188

are hopefully relevant tunes

**Comment by rusefillc** [comment]
https://rusefi.com/online/view.php?msq=191

BinaryProtocol - From rusEFI tune CRC16 0x161 353

crc16=353 matches new "crc16" gauge

![image](https://user-images.githubusercontent.com/48498823/90273038-4f627000-de2c-11ea-9014-75a92a48ad26.png)

**Comment by rusefillc** [comment]
https://rusefi.com/online/view.php?msq=192

4621 is proper new CRC16
![image](https://user-images.githubusercontent.com/48498823/90273142-7faa0e80-de2c-11ea-9cd7-3fae4db1ec5b.png)

https://rusefi.com/online/view.php?log=24 seem to have both valid crc16

**Comment by rusefillc** [comment]
crc16 was wrong because of wrong engine_type definition in TS project. This is now fixed and engine type in TS project uses new feature of code generator

https://github.com/rusefi/rusefi/issues/1693 created to address similar issue on a larger scale

**Comment by rusefillc** [comment]
@andreika-git fresh set of tunes & log:

https://rusefi.com/online/view.php?msq=193
https://rusefi.com/online/view.php?msq=194

https://rusefi.com/online/view.php?log=25

**Comment by andreika-git** [comment]
`URL to diff to previous tune
`
What's the text of the url? And if there's only 1 record (no previous one), what text should it be?

**Comment by rusefillc** [comment]
for now let's use "XXX" text just to have a prototype

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/b5717961f932105e34f070034442ba5dde2f603e
