### ISSUE TITLE
link to .ini file to offer download

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#81]
at the moment I have https://rusefi.com/online/ini/rusefi/2020/07/23/all/1241418013.ini which browser opens as text

We need this or different URL to offer file save right away

@andreika-git do you know relevant google keywords?

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/87ed40524df87512fdec6c58fa4fecb48103ec7b
