### ISSUE TITLE
Feature request: Tune delete feature

### ISSUE THREAD

**Issue by stefanst** [rusefi/web_backend#86]
I had "auto-update tune" selected and was busy changing some basic values. Every time I changed a vaule, a new tune was uploaded. Which is great if you're actively tuning and trying to log, but at some point it also generates a lot of clutter. We need to be able to delete tunes, or at least hide them in some way.
I believe I also suggested at some point to have "Base Tune" as a characteristic. This should be a tune that reliably runs an engine in a specific configuration and can be used to tweak further.

**Comment by rusefillc** [comment]
issues like #89 are increasing the priority of this feature request

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/65d6589336b64d223f81be6f9af0c1a9add2ec7c
