### ISSUE TITLE
Signature: XXX - XXX should be a link to .ini file

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#88]
open
https://rusefi.com/online/view.php?msq=89

We have "Signature: rusEFI 2020.07.21.mre_f4.4281735147" text - the signature part should be a URL to download that .ini file

Please also remove "Tuning SW:" and "Format Version:" maybe while we are touching this screen?

**Comment by rusefillc** [comment]
Links would point at https://rusefi.com/online/ini/rusefi/2020/ subfolders

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/f59302c6424f7504a6574d199710e6f6a7d06c46
