### ISSUE TITLE
log upload is broken

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#93]
latest TS log would not upload

![image](https://user-images.githubusercontent.com/48498823/90063203-02a95880-dcb7-11ea-8add-e28c3b09cd93.png)

can we please make the error message more specific? it would be useful to print at least one exact name of a missing field

logs attached

[DataLogs.zip](https://github.com/rusefi/web_backend/files/5065427/DataLogs.zip)

**Comment by andreika-git** [comment]
'can we please make the error message more specific? it would be useful to print at least one exact name of a missing field'
It's already specific, it contains the exact list of missing fields. ALL of them are missing. And you can verify it easily by opening the log file in MLV.
P.S. I don't think it's the "web_backend" issue.

**Comment by rusefillc** [comment]
operator error - it was partial field save TS profile
