### ISSUE TITLE
same compression is displayed for all tunes on the engine wrongly

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#94]
Note that all tunes show same 6.2 CR

![image](https://user-images.githubusercontent.com/48498823/90138472-0e436080-dd45-11ea-9cd8-2a92ccaea710.png)

in reality all tunes have different CR https://rusefi.com/online/view.php?msq=184

**Comment by rusefillc** [comment]
Oh looks like that's a feature?

![image](https://user-images.githubusercontent.com/48498823/90138714-68dcbc80-dd45-11ea-901c-1def209470e1.png)

**Comment by mi-hol** [comment]
@rusefillc Fixed apparently, please close
![image](https://user-images.githubusercontent.com/22799428/215091837-2f6762c2-d2a8-42ac-bd9e-2a66ff4274aa.png)
