### ISSUE TITLE
I've uploaded a tune and get a screen full of warnings

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#97]
After uploading https://rusefi.com/online/view.php?msq=205 I got

![image](https://user-images.githubusercontent.com/48498823/91647621-c736ba00-ea2a-11ea-844d-8d8d168bbf5d.png)

**Comment by rusefillc** [comment]
A wild guess is that "{1/10} in field declaration could be the cause of this?

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/rusefi/issues/1735

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/2666c8a3558e57068c99dac2c6bc29bc73565570
